#
# Know Your IP documentation build configuration file, created by
# sphinx-quickstart on Tue Jan 23 19:17:03 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, os.path.abspath("../"))
sys.path.insert(1, os.path.abspath("../../"))


# Read project metadata from pyproject.toml
def read_pyproject_metadata():
    """Read project metadata from pyproject.toml"""
    try:
        pyproject_path = Path(__file__).parent.parent.parent / "pyproject.toml"
        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)
        return data.get("project", {})
    except (FileNotFoundError, tomllib.TOMLDecodeError) as e:
        print(f"Warning: Could not read pyproject.toml: {e}")
        return {}


# Load project metadata
project_metadata = read_pyproject_metadata()


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# MyST parser will handle .md files
source_suffix = ['.md']

# The master toctree document.
master_doc = "index"

# MyST parser configuration
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
    "attrs_inline",
    "linkify",
]

# Enable cross-referencing
myst_heading_anchors = 3
myst_all_links_external = False

# Autodoc configuration
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
    "special-members": "__init__",
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"

# Autosummary configuration - disabled to avoid RST generation
autosummary_generate = False
autosummary_imported_members = False

# Napoleon configuration (for Google/NumPy style docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False

# Intersphinx configuration (links to other documentation)
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "sklearn": ("https://scikit-learn.org/stable", None),
    "torch": ("https://pytorch.org/docs/stable", None),
}

# General information about the project.
project = project_metadata.get("name", "ethnicolr2")

# Extract authors from pyproject.toml
authors_list = project_metadata.get("authors", [])
if authors_list:
    author_names = [
        author.get("name", "") for author in authors_list if author.get("name")
    ]
    author = ", ".join(author_names)
else:
    author = "Rajashekar Chintalapati, Suriyan Laohaprapanon, Gaurav Sood"

copyright = f"2023, {author}"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# Extract version from pyproject.toml
project_version = project_metadata.get("version", "0.1.4")

# The short X.Y version.
version = project_version
# The full version, including alpha/beta/rc tags.
release = project_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# GitHub Pages configuration
# Extract repository URL from pyproject.toml
project_urls = project_metadata.get("urls", {})
repository_url = project_urls.get("Repository", "https://github.com/appeler/ethnicolr2")

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "light_logo": "logo-light.png",
    "dark_logo": "logo-dark.png",
    "source_repository": repository_url,
    "source_branch": "main",
    "source_directory": "docs/source/",
    "edit_page_text": "Edit this page",
    "navigation_with_keys": True,
    "top_of_page_buttons": ["edit", "view"],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Generate GitHub Pages URL from repository URL
if "github.com" in repository_url:
    # Convert https://github.com/user/repo to https://user.github.io/repo/
    repo_parts = repository_url.replace("https://github.com/", "").split("/")
    if len(repo_parts) >= 2:
        html_baseurl = f"https://{repo_parts[0]}.github.io/{repo_parts[1]}/"
    else:
        html_baseurl = "https://appeler.github.io/ethnicolr2/"
else:
    html_baseurl = "https://appeler.github.io/ethnicolr2/"

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# Furo theme handles sidebars automatically, so we remove custom sidebar templates
# html_sidebars = {}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "ethnicolr2doc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "ethnicolr.tex",
        "ethnicolr2 Documentation",
        "Rajashekar Chintalapati, Suriyan Laohaprapanon, Gaurav Sood",
        "manual",
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "ethnicolr2", "ethnicolr2 Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "ethnicolr2",
        "ethnicolr2 Documentation",
        author,
        "ethnicolr2",
        "Predict Race and Ethnicity from Names",
        "Miscellaneous",
    ),
]
